# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: sessions-app

services:
  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    command: ["valkey-server", "--save", "60", "1", "--loglevel", "warning"]

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ../app/init.sql:/docker-entrypoint-initdb.d/init.sql

  data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample-data
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USERNAME=admin
      - DB_PASSWORD=password

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - valkey
      - postgres
      - data
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USERNAME=admin
      - DB_PASSWORD=password
